image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # Запускаем SUT,
  # имя файла SUT будет отличаться в каждой задаче.
  # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
  # обязательно должен быть для запуска SUT в CI
  - chmod +x gradlew
  - java -jar ./artifacts/app-card-delivery.jar &              # Подождать, пока сервер запустится


build_script:
  - ./gradlew test --info -Dselenide.headless=true