name: Java CI with Gradle

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      app:
        image: openjdk:11
        ports:
          - 9999:9999
        options: --health-cmd="curl -f http://localhost:9999 || exit 1" --health-interval=5s --health-timeout=5s --health-retries=5
        volumes:
          - ./artifacts:/artifacts
        working-directory: /artifacts
        run: java -jar app-card-delivery.jar

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Wait for app to start
        run: sleep 15

      - name: Run tests with Gradle
        env:
          SELENIDE_HEADLESS: true
        run: ./gradlew test --info -Dselenide.headless=true

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/reports/allure-report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            build/test-results
            build/reports/tests